name: copy_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  copy:
    path: ../

dev_dependencies:
  build_runner: ^1.7.2
  flutter_test:
    sdk: flutter

dependency_overrides:
  copy:
    path: ../

flutter:
  uses-material-design: true
