name: copy
version: 0.1.2
authors:
  - tbm98 <tbm98.dev@gmail.com>
description: Automatically generating `copyWith` extensions code for classes with `@Copyable()` annotation.
repository: https://github.com/tbm98/copy
homepage: https://github.com/tbm98/copy
issue_tracker: https://github.com/tbm98/copy/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.0.0